use std::collections::HashSet;
use std::sync::{Arc, Mutex};

use crate::errors::{OalError, Result};

use engage_ux_core::geometry::Rectangle;

/// Opaque handle representing a drawable surface in the backend.
pub type SurfaceHandle = u128;

/// Descriptor used when creating or reconfiguring a surface.
///
/// Values are expressed in device-independent logical units (not pixels).
/// Prefer using the builder API `SurfaceDescriptor::builder()` to construct
/// descriptors so callers can set only the fields they care about.
#[derive(Debug, Clone)]
pub struct SurfaceDescriptor {
	/// Logical width of the surface in device-independent units.
	pub width: f32,
	/// Logical height of the surface in device-independent units.
	pub height: f32,
}

/// Backwards-compatible alias used across the crate. Some modules refer to
/// `SurfaceParams`; keep that name as an alias to avoid widespread churn.
pub type SurfaceParams = SurfaceDescriptor;

/// Builder for `SurfaceDescriptor`.
pub struct SurfaceDescriptorBuilder {
	width: f32,
	height: f32,
}

impl SurfaceDescriptor {
	/// Create a new builder for `SurfaceDescriptor`.
	pub fn builder() -> SurfaceDescriptorBuilder {
		SurfaceDescriptorBuilder {
			width: 0.0,
			height: 0.0,
		}
	}
}

impl SurfaceDescriptorBuilder {
	/// Set the logical width for the descriptor.
	pub fn width(mut self, w: f32) -> Self {
		self.width = w;
		self
	}

	/// Set the logical height for the descriptor.
	pub fn height(mut self, h: f32) -> Self {
		self.height = h;
		self
	}

	/// Build the `SurfaceDescriptor`.
	pub fn build(self) -> SurfaceDescriptor {
		SurfaceDescriptor {
			width: self.width,
			height: self.height,
		}
	}
}

/// Events generated by the backend for the platform layer to consume.
#[derive(Debug, Clone)]
pub enum PlatformEvent {
	/// The backend requests a new frame for the given surface.
	FrameRequested {
		/// Surface handle identifying which surface needs a frame.
		surface: SurfaceHandle,
	},
	/// The backend requests that the given surface be closed.
	CloseRequested {
		/// Surface handle identifying which surface should be closed.
		surface: SurfaceHandle,
	},
}

/// Minimal Backend trait describing platform-specific surface/window
/// management. Implementations should map platform-specific errors to
/// `OalError` where appropriate.
pub trait Backend: Send + Sync {
	/// Create a new surface using the provided `SurfaceDescriptor`.
	fn create_surface(&self, params: SurfaceDescriptor) -> Result<SurfaceHandle>;

	/// Poll for pending platform events. Returns a list of `PlatformEvent`s.
	fn poll_events(&self) -> Vec<PlatformEvent>;

	/// Present the given region(s) for the surface. `dirty` contains logical
	/// rectangles that need to be presented.
	fn present_frame(&self, surface: SurfaceHandle, dirty: &[Rectangle]) -> Result<()>;

	/// Invalidate the provided logical rectangles on the surface. Backends
	/// may use this as a hint to repaint or flush regions.
	fn invalidate_region(&self, surface: SurfaceHandle, rects: &[Rectangle]) -> Result<()>;

	/// Destroy the surface and free associated resources.
	fn destroy_surface(&self, surface: SurfaceHandle) -> Result<()>;

	/// Reconfigure an existing surface (size, formats, etc.). Backends that
	/// can efficiently reconfigure should implement this instead of requiring
	/// destroy+create on resize.
	fn reconfigure_surface(&self, surface: SurfaceHandle, params: SurfaceDescriptor) -> Result<()>;

	/// Set the title for an existing surface/window. Backends that support
	/// native window titles should update the platform window title when
	/// possible. For headless backends this is a no-op.
	fn set_surface_title(&self, surface: SurfaceHandle, title: &str) -> Result<()>;

	/// Submit a render job to be executed on the backend's GPU/context-owning
	/// thread. The job is a boxed `RenderCallback` which will be invoked with
	/// a backend-specific context passed as `&mut dyn Any`. Backends should
	/// document the concrete context type they provide (for example the
	/// winit/wgpu backend will provide a `WgpuRenderContext`).
	fn submit_render(&self, surface: SurfaceHandle, job: Box<dyn RenderCallback>) -> Result<()>;
}

/// Simple headless backend implementation used for testing and examples.
///
/// This backend does not create real platform surfaces; instead it tracks
/// created handles and provides no-op implementations for present/invalidate.
#[derive(Debug, Clone)]
pub struct HeadlessBackend {
	inner: Arc<Mutex<HeadlessInner>>,
}

/// A boxed render job. Implementors should downcast the provided `backend_ctx`
/// to the concrete context type the backend documents and perform rendering
/// using the provided GPU objects.
pub trait RenderCallback: Send {
	/// Called on the backend thread with a backend-specific context passed
	/// as a mutable erased `Any` reference. Backends should document the
	/// concrete context type they provide (for example the winit/wgpu
	/// backend provides a `WgpuRenderContext` reference during Present).
	///
	/// Using a mutable reference avoids boxing backend-local references and
	/// keeps the callback invocation lightweight.
	fn call_box(self: Box<Self>, backend_ctx: &mut dyn std::any::Any) -> Result<()>;
}

impl<F: Send + FnOnce(&mut dyn std::any::Any) -> Result<()>> RenderCallback for F {
	fn call_box(self: Box<F>, backend_ctx: &mut dyn std::any::Any) -> Result<()> {
		// Move out the FnOnce and call it.
		let f = *self;
		f(backend_ctx)
	}
}

#[derive(Debug)]
struct HeadlessInner {
	next_id: u128,
	surfaces: HashSet<SurfaceHandle>,
}

impl HeadlessBackend {
	/// Create a new `HeadlessBackend` instance for tests and examples.
	pub fn new() -> Self {
		Self {
			inner: Arc::new(Mutex::new(HeadlessInner {
				next_id: 1,
				surfaces: HashSet::new(),
			})),
		}
	}
}

impl Backend for HeadlessBackend {
	fn create_surface(&self, _params: SurfaceDescriptor) -> Result<SurfaceHandle> {
		let mut guard = self
			.inner
			.lock()
			.map_err(|_| OalError::PoisonedLock("headless backend mutex poisoned".into()))?;
		let id = guard.next_id;
		guard.next_id = guard.next_id.saturating_add(1);
		guard.surfaces.insert(id);
		Ok(id)
	}

	fn poll_events(&self) -> Vec<PlatformEvent> {
		// Headless backend does not generate platform events by default.
		Vec::new()
	}

	fn present_frame(&self, _surface: SurfaceHandle, _dirty: &[Rectangle]) -> Result<()> {
		Ok(())
	}

	fn invalidate_region(&self, _surface: SurfaceHandle, _rects: &[Rectangle]) -> Result<()> {
		Ok(())
	}

	fn destroy_surface(&self, surface: SurfaceHandle) -> Result<()> {
		let mut guard = self
			.inner
			.lock()
			.map_err(|_| OalError::PoisonedLock("headless backend mutex poisoned".into()))?;
		guard.surfaces.remove(&surface);
		Ok(())
	}

	fn reconfigure_surface(
		&self,
		_surface: SurfaceHandle,
		_params: SurfaceDescriptor,
	) -> Result<()> {
		// No-op for headless backend.
		Ok(())
	}

	fn set_surface_title(&self, _surface: SurfaceHandle, _title: &str) -> Result<()> {
		// Headless backend does not track platform titles; no-op.
		Ok(())
	}

	fn submit_render(&self, _surface: SurfaceHandle, _job: Box<dyn RenderCallback>) -> Result<()> {
		// Headless backend cannot execute GPU jobs; return an error to
		// indicate unsupported operation.
		Err(OalError::Renderer(
			"submit_render not supported for headless backend".into(),
		))
	}
}

impl Default for HeadlessBackend {
	fn default() -> Self {
		Self::new()
	}
}
