[package]
name = "engage-ux-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Core functionality for Engage UX - a cross-platform UI toolkit"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
